main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.NewSetsListView.as_view(), name='index'),
    path('hot', views.HotPricesView.as_view(), name='hot'),
    path('all', views.LegoSetsListView.as_view(), name='all_lego_sets'),
    path('<int:pk>', views.LegoSetDetailView.as_view(), name='lego_set_info'),
    path('search', views.search, name='search'),
    path('search_by_name', views.SearchSetsListView.as_view(), name='search_by_name'),
    path('series/<int:pk>', views.SerieSetsListView.as_view(), name='serie_lego_sets'),
    path('series', views.LegoSeries.as_view(), name='series'),
]

main/models.py
from django.db import models
from django.contrib import admin
from django.contrib.postgres.fields import IntegerRangeField


class LegoSet(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=250, blank=True)
    serie = models.ForeignKey('Serie', blank=True, null=True, on_delete=models.DO_NOTHING, related_name='lego_sets')
    description = models.TextField(blank=True)
    ages = IntegerRangeField(blank=True, null=True)
    details = models.IntegerField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)  # TODO после импорта БД добавить auto_now_add=True

    def get_ages_str(self) -> str:
        """Возвращает значение ages (IntegerRangeField) в читаемом формате строки"""
        if self.ages:
            ages_list = [i for i in str(self.ages).strip('\'[)').split(', ') if i != 'None']
            if len(ages_list) == 2:
                # Особенность IntegerRangeField - правая граница не включается
                ages_list[1] = str(int(ages_list[1]) - 1)
                ages_str = ' - '.join(ages_list)
            else:
                ages_str = ages_list[0] + '+'
            return ages_str
        else:
            return 'нет информации'

    @admin.display(boolean=True)
    def image_exists(self):
        return self.images.exists()

    class Meta:
        db_table = 'lego_sets'
        verbose_name = 'Набор LEGO'
        verbose_name_plural = 'Наборы LEGO'

    def __str__(self):
        return self.name


class Price(models.Model):
    lego_set = models.ForeignKey('LegoSet', on_delete=models.CASCADE, related_name='prices')
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE)
    # Цена без скидки
    full_price = models.IntegerField(blank=True, null=True)
    # Цена со кидкой
    discount_price = models.IntegerField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)  # TODO после импорта БД добавить auto_now_add=True

    class Meta:
        db_table = 'prices'
        verbose_name = 'Цена'
        verbose_name_plural = 'Цены'

    def __str__(self):
        return str(self.created_at) + ' ' + str(self.shop) + ' - ' + str(self.lego_set_id)


class Shop(models.Model):
    name = models.CharField(max_length=50)
    domain = models.CharField(max_length=150)
    lego_url = models.CharField(max_length=500)

    class Meta:
        db_table = 'shops'
        verbose_name = 'Мазазин'
        verbose_name_plural = 'Магазины'

    def __str__(self):
        return str(self.name)


class Serie(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'series'
        verbose_name = 'Серия LEGO'
        verbose_name_plural = 'Серии LEGO'

    def __str__(self):
        return self.name


class Statistic(models.Model):
    lego_set = models.OneToOneField('LegoSet', on_delete=models.CASCADE)
    minimal_price = models.IntegerField(blank=True, null=True)
    minimal_price_date = models.DateField(null=True)
    middle_price = models.IntegerField(blank=True, null=True)
    today_price = models.IntegerField(blank=True, null=True)
    today_discount = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'statistics'
        verbose_name = 'Статистика цен'
        verbose_name_plural = 'Статистика цен на набор'

    def __str__(self):
        return self.lego_set.name


class Link(models.Model):
    url = models.CharField(max_length=500)
    lego_set = models.ForeignKey('LegoSet', on_delete=models.CASCADE, related_name='links')
    shop = models.ForeignKey('Shop', on_delete=models.CASCADE, related_name='links')

    class Meta:
        db_table = 'links'
        verbose_name = 'Ссылка'
        verbose_name_plural = 'Ссылки'


class Image(models.Model):
    class ImageType(models.TextChoices):
        MAX = 'MX', 'Большое изображение'
        MIN = 'MN', 'Маленькое изображение'

    type = models.CharField(
        max_length=2,
        choices=ImageType.choices,
        blank=True
    )

    image_path = 'static/main/images'
    filename = models.ImageField(upload_to=image_path, blank=True, null=True)
    lego_set = models.ForeignKey('LegoSet', on_delete=models.CASCADE, related_name='images')

    class Meta:
        db_table = 'images'
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

main/views.py
from datetime import date
from typing import Optional

from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.db.models import Prefetch
from psycopg2.extras import NumericRange

from .models import LegoSet, Price, Serie, Image


class LegoSetDetailView(DetailView):
    """Вывод всех свойств объекта LegoSet"""
    model = LegoSet
    # получаем все связанные объекты из БД
    queryset = LegoSet.objects.prefetch_related('prices').prefetch_related('links').prefetch_related(
        'statistic').prefetch_related(Prefetch('images', queryset=Image.objects.filter(type='MX'),
                                               to_attr='big_image'))
    template_name = 'main/lego_set_detailview.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ages'] = self.object.get_ages_str()
        context['prices'] = self._get_ordered_prices()
        context['today_prices'], context['today_minprice'] = self._get_today_prices()
        return context

    def _get_ordered_prices(self) -> list[list]:
        """Возвращает список списков, отсортированный по датам
        [date, shop1_full, shop1_disc, shop2_full, shop2_disc][...]"""
        prices_dict = {}
        for price_entry in self.object.prices.all():
            if str(price_entry.created_at) not in prices_dict:
                prices_dict[str(price_entry.created_at)] = [''] * 4
            prices_dict[str(price_entry.created_at)][price_entry.shop.id * 2 - 2] = price_entry.full_price
            prices_dict[str(price_entry.created_at)][price_entry.shop.id * 2 - 1] = price_entry.discount_price
        prices_list = [[date_value] + prices_dict[date_value] for date_value in sorted(prices_dict, reverse=True)]
        return prices_list

    def _get_today_prices(self) -> tuple[dict, Optional[int]]:
        """Возвращает словарь {shop_id: today_price} и цену продажи на сегодня"""
        today_prices_queryset = self.object.prices.filter(created_at=date.today())
        today_prices_dict = {
            price.shop.id: (min(price.full_price, price.discount_price) if price.full_price and price.discount_price
                            else None) for price in today_prices_queryset
        }
        today_minprice = min([price for price in today_prices_dict.values()]) if today_prices_dict else None
        return today_prices_dict, today_minprice


class LegoSetsListView(ListView):
    """Универсальный ListView для наборов"""

    model = LegoSet
    template_name = 'main/lego_sets_listview.html'
    paginate_by = 20
    ordering = ['id']

    # Значения по умолчанию для фильтров
    price_from = 0
    price_to = 50000
    age_from = 0
    age_to = 21
    details_from = 0
    details_to = 5000

    def get_queryset(self):
        # Определяем параметр pagination
        pagination = self.request.GET.get('pag')
        pagination_variants = ('20', '40', '60', '100')
        if pagination in pagination_variants:
            self.paginate_by = pagination
        else:
            self.paginate_by = 20

        # Определяем параметр ordering
        ordering = self.request.GET.get('ordering')
        # TODO прикрутить возврат в шаблон значений параметра, по которому производилась сортировка
        ordering_variants = {'pr': 'statistic__today_price', 'ds': 'statistic__today_discount',
                             'ag': 'ages', 'dt': 'details', 'nw': 'created_at',
                             '-pr': '-statistic__today_price', '-ds': '-statistic__today_discount',
                             '-ag': '-ages', '-dt': '-details', '-nw': '-created_at'}
        if ordering in ordering_variants.keys():
            # дополнительный параметр для того, чтобы объекты были отсортированы одинаково при одинаковых запросах
            self.ordering = [ordering_variants[ordering], 'id']

        queryset = super().get_queryset().prefetch_related('statistic').prefetch_related(
            Prefetch('images', queryset=Image.objects.filter(type='MN'), to_attr='small_image'))

        # Определяем параметры фильтрации:
        # цена от
        if self.request.GET.get('price_from') and self.request.GET.get('price_from').isdecimal() and \
                0 <= int(self.request.GET.get('price_from')) < 50000:
            self.price_from = int(self.request.GET.get('price_from'))
            queryset = queryset.filter(statistic__today_price__gt=self.price_from)

        # цена до
        if self.request.GET.get('price_to') and self.request.GET.get('price_to').isdecimal() and \
                0 <= int(self.request.GET.get('price_to')) < 50000:
            self.price_to = int(self.request.GET.get('price_to'))
            queryset = queryset.filter(statistic__today_price__lt=self.price_to)

        # возраст от до
        if self.request.GET.get('age_from') and self.request.GET.get('age_from').isdecimal() and \
                0 <= int(self.request.GET.get('age_from')) <= 18 and self.request.GET.get('age_to') \
                and self.request.GET.get('age_to').isdecimal() and 0 <= int(self.request.GET.get('age_to')) <= 18:
            age_from = int(self.request.GET.get('age_from'))
            age_to = int(self.request.GET.get('age_to')) + 1
            ages_filter = NumericRange(age_from, age_to)
            queryset = queryset.filter(Q(ages__overlap=ages_filter) &
                                       Q(ages__gte=NumericRange(age_from, None), ages__upper_inf=True))

        # деталей от
        if self.request.GET.get('details_from') and self.request.GET.get('details_from').isdecimal() and \
                0 <= int(self.request.GET.get('details_from')) < 5000:
            self.details_from = self.request.GET.get('details_from')
            queryset = queryset.filter(details__gt=self.details_from)

        # деталей до
        if self.request.GET.get('details_to') and self.request.GET.get('details_to').isdecimal() and \
                0 <= int(self.request.GET.get('details_to')) < 5000:
            self.details_to = int(self.request.GET.get('details_to'))
            queryset = queryset.filter(details__lt=self.details_to)

        # только со скидкой
        if self.request.GET.get('discount') and self.request.GET.get('discount') == 'on':
            queryset = queryset.filter(statistic__today_discount__gt=0)

        # изменение очередности queryset для того, чтобы значения None были в конце
        if self.ordering[0] == '-statistic__today_price':
            qs = queryset.annotate(null_position=Count('statistic__today_price')).order_by(
                '-null_position', '-statistic__today_price')
        elif self.ordering[0] == '-statistic__today_discount':
            qs = queryset.annotate(null_position=Count('statistic__today_discount')).order_by(
                '-null_position', '-statistic__today_discount')
        elif self.ordering[0] == 'ages' or self.ordering[0] == '-ages':
            qs = queryset
            for lego_set in qs:
                lego_set.ages_str = lego_set.get_ages_str()
        else:
            qs = queryset
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pagination'] = self.request.GET.get('pag')
        context['ordering'] = self.request.GET.get('ordering')
        context['page_title'] = "Все наборы LEGO"
        return context


class NewSetsListView(LegoSetsListView):
    """ListView для index (5 последних добавленных на сайт наборов)"""
    template_name = 'main/index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.order_by('-created_at', '-id')[0:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lego_sets_count'] = LegoSet.objects.count()  # TODO снизить нагрузку на базу - занести в кэш?
        context['prices_count'] = Price.objects.count()  # TODO снизить нагрузку на базу - занести в кэш?
        return context


class HotPricesView(LegoSetsListView):
    """ListView для hot (Лучшие цены)"""

    def get_queryset(self):
        qs = super().get_queryset().filter(statistic__today_discount__gt=0)
        if self.ordering == ['id']:
            return qs.order_by('-statistic__today_discount', 'id')
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Скидки на наборы LEGO"
        return context


class SearchSetsListView(LegoSetsListView):
    """ListView для search (Поиск наборов)"""
    paginate_by = None

    def get_queryset(self):
        # TODO deployment CREATE EXTENSION pg_trgm;
        qs = super().get_queryset()
        search_text = str(self.request.GET['search_request'])
        qs = qs.annotate(similarity=TrigramSimilarity('name', search_text)) \
            .filter(similarity__gt=0.05)
        if self.ordering == ['id']:
            return qs.order_by('-similarity')
        # TODO разобраться с параметром similarity, подобрать нужное значение
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_request'] = str(self.request.GET['search_request'])
        context['page_title'] = "Поиск наборов " + str(self.request.GET['search_request'])
        return context


class SerieSetsListView(LegoSetsListView):
    """ListView для наборов из одной серии"""

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(serie_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "Наборы LEGO из серии " + Serie.objects.get(id=self.kwargs['pk']).name
        return context


class LegoSeries(ListView):
    """ListView для серий"""

main/templates/main/index.html
{% extends 'main/main_layout.html' %}
{% load static %}
{% load url_replace %}

{% block title %} TOYPRICES.RU {% endblock %}

{% block content %}
    <div class="site_description">
        <h1>Мониторинг цен на наборы LEGO</h1>
        <p>Данный сайт не является интернет-магазином!</p>
        <p>На сайте опубликованы данные об истории цен на наборы LEGO в популярных интернет-магазинах.</p>
        <p>Данный веб-сайт является независимым и не был санкционирован или создан Группой компаний LEGO®</p>
        <p>Всего на сайте: <b>{{ lego_sets_count }}</b> наборов LEGO и <b>{{ prices_count }}</b> записей о ценах</p>
    </div>
    <div class="index_wrapper">
        <h2>Последние добавленные наборы LEGO:</h2>
        <div class="products_inner">
            {% for legoset in legoset_list %}
                <div class="product_wrapper div_href">
                    <div class="product_image">
                        <img src="{% static legoset.small_image.0.filename|dds %}" alt="{{ legoset.id }}">
                    </div>
                    <div class="product_info">
                        <div class="product_id"># {{ legoset.id }}</div>
                        <div class="product_added"> Добавлен: {{ legoset.created_at }} </div>
                        <div class="product_main_info">
                            <div class="product_param product_price
                                {% if not legoset.statistic.today_price %}
                                    hidden
                                {% endif %}">
                                {% if legoset.statistic.today_price %}
                                    {{ legoset.statistic.today_price }} Р
                                {% endif %}
                            </div>
                            <div class="product_param product_discount
                                    {% if not legoset.statistic.today_discount or legoset.statistic.today_discount <= 0 %}
                                        hidden
                                    {% endif %}
                                    " style="background-color:
                                    {% if legoset.statistic.today_discount < 10 %}
                                        PaleGreen
                                    {% elif legoset.statistic.today_discount < 10 %}
                                        MediumSpringGreen
                                    {% elif legoset.statistic.today_discount < 20 %}
                                        GreenYellow
                                    {% elif legoset.statistic.today_discount < 30 %}
                                        Yellow
                                    {% elif legoset.statistic.today_discount < 40 %}
                                        DarkOrange
                                    {% elif legoset.statistic.today_discount <= 50 %}
                                        OrangeRed
                                    {% elif legoset.statistic.today_discount > 50 %}
                                        Red
                                    {% endif %}
                                    "> {{ legoset.statistic.today_discount }}%
                            </div>
                        </div>

                        <a href="/{{ legoset.id }}">{{ legoset.name }}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

main/templates/main/lego_sets_listview.html
{% extends 'main/main_layout.html' %}
{% load static %}
{% load url_replace %}

{% block title %} {{ page_title }} {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'main/css/sliders.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="sidebar">
            <button id="expand_sorting" class="sort-by">Развернуть меню сортировки и фильтров</button>
            <button id="remove_sorting" class="sort-by">Cвернуть меню сортировки и фильтров</button>
            <form class="sidebar_list" action="" method="get">
                <div class="sort-by">
                    <label for="">Наборов на странице:
                        <select name="pag" id="pagination-select">
                            <option
                                    {% if pagination == '20' %}
                                        selected
                                    {% endif %}
                                        value="20">20
                            </option>
                            <option
                                    {% if pagination == '40' %}
                                        selected
                                    {% endif %}
                                        value="40">40
                            </option>
                            <option
                                    {% if pagination == '60' %}
                                        selected
                                    {% endif %}
                                        value="60">60
                            </option>
                            <option
                                    {% if pagination == '100' %}
                                        selected
                                    {% endif %}
                                        value="100">100
                            </option>
                        </select>
                    </label>
                </div>
                <div class="sort-by">Отсортировать по:</div>
                <button type="submit" name="ordering" class="ordering-button
                    {% if ordering == 'pr' %} active" value='-pr'>Цене&#9650;
                {% elif ordering == '-pr' %} active" value='pr'>Цене&#9660;
                {% else %}" value='pr'>Цене
                {% endif %}
                </button>
                <button type="submit" name="ordering" class="ordering-button
                    {% if ordering == 'ds' %} active"
                        value='-ds'>Скидке&#9650;
                {% elif ordering == '-ds' %} active" value='ds'>Скидке
                    &#9660;
                {% else %}" value='-ds'>Скидке
                {% endif %}
                </button>
                <button type="submit" name="ordering" class="ordering-button
                    {% if ordering == 'ag' %} active" value='-ag'>Возрасту&#9650;
                {% elif ordering == '-ag' %} active" value='ag'>Возрасту&#9660;
                {% else %}" value='ag'>Возрасту
                {% endif %}
                </button>
                <button type="submit" name="ordering" class="ordering-button
                    {% if ordering == 'dt' %} active" value='-dt'>Деталям&#9650;
                {% elif ordering == '-dt' %} active" value='dt'>Деталям&#9660;
                {% else %}" value='dt'>Деталям
                {% endif %}
                </button>
                <button type="submit" name="ordering" class="ordering-button
                    {% if ordering == 'nw' %} active" value='-nw'>Новизне&#9650;
                {% elif ordering == '-nw' %} active" value='nw'>Новизне&#9660;
                {% else %}" value='-nw'>Новизне
                {% endif %}
                </button>

                <div class="sort-by">Фильтры:</div>
                Цена:
                <div class="ordering-button">
                    от <input type="number" class="price-range" id="price-from" name="price_from"
                              value="{{ request.GET.price_from }}">
                    до <input type="number" class="price-range" id="price-to" name="price_to"
                              value="{{ request.GET.price_to }}">

                    <div id="slider-price-range" class="slider-range"></div>
                </div>
                Возраст:
                <div class="ordering-button">
                    от <input type="number" class="price-range" id="age-from" name="age_from"
                              value="{{ request.GET.age_from }}">
                    до <input type="number" class="price-range" id="age-to" name="age_to"
                              value="{{ request.GET.age_to }}">

                    <div id="slider-age-range" class="slider-range"></div>
                </div>
                Деталей:
                <div class="ordering-button">
                    от <input type="number" class="price-range" id="details-from" name="details_from"
                              value="{{ request.GET.details_from }}">
                    до <input type="number" class="price-range" id="details-to" name="details_to"
                              value="{{ request.GET.details_to }}">
                    <div id="slider-details-range" class="slider-range"></div>
                </div>
                <input id="input-checkbox" type="checkbox" name="discount" {% if request.GET.discount %}
                       checked {% endif %}>
                <div class="ordering-button">
                    <label for="input-checkbox">
                        Только со скидкой
                    </label>
                </div>
                <button type="submit" class="ordering-button" id="filter-submit">Применить фильтры</button>
                <input type="hidden" name="search_request" value="{{ request.GET.search_request }}">
            </form>
        </div>
        <div class="products_outer">
            {% if is_paginated %}
                <div class="pagination">
                    {% for page in page_obj.paginator.page_range %}
                        {% if page == 1 or page >= page_obj.number|add:'-3' and page <= page_obj.number|add:'3' or page == page_obj.paginator.num_pages %}
                            <a class="paginator_page_num {% if page == page_obj.number %} active {% endif %}"
                               href="?{% paginator_url_replace request 'page' page %}">
                                {{ page }}
                            </a>
                        {% else %}
                            {% if page == page_obj.number|add:'-4' or page == page_obj.number|add:'4' %}
                                <span class="paginator_page_ellipsis">...</span>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="products_inner">
                {% for legoset in legoset_list %}
                    <div class="product_wrapper div_href">
                        <div class="product_image">
                            <img src="{% static legoset.small_image.0.filename|dds %}" alt="{{ legoset.id }}">
                        </div>
                        <div class="product_info">
                            <div class="product_id"># {{ legoset.id }}</div>
                            {% if ordering == 'ag' or ordering == '-ag' %}
                                возраст: {{ legoset.ages_str }}
                            {% elif ordering == 'dt' or ordering == '-dt' %}
                                деталей: {{ legoset.details }}
                            {% elif ordering == 'nw' or ordering == '-nw' %}
                                {{ legoset.created_at|date:"d.m.Y" }}
                            {% endif %}
                            <div class="product_main_info">
                                <div class="product_param product_price
                                {% if not legoset.statistic.today_price %}
                                    hidden
                                {% endif %}">
                                    {% if legoset.statistic.today_price %}
                                        {{ legoset.statistic.today_price }} Р
                                    {% endif %}
                                </div>
                                <div class="product_param product_discount
                                    {% if not legoset.statistic.today_discount or legoset.statistic.today_discount <= 0 %}
                                        hidden
                                    {% endif %}
                                    " style="background-color:
                                        {% if legoset.statistic.today_discount < 10 %}
                                            PaleGreen
                                        {% elif legoset.statistic.today_discount < 10 %}
                                            MediumSpringGreen
                                        {% elif legoset.statistic.today_discount < 20 %}
                                            GreenYellow
                                        {% elif legoset.statistic.today_discount < 30 %}
                                            Yellow
                                        {% elif legoset.statistic.today_discount < 40 %}
                                            DarkOrange
                                        {% elif legoset.statistic.today_discount <= 50 %}
                                            OrangeRed
                                        {% elif legoset.statistic.today_discount > 50 %}
                                            Red
                                        {% endif %}
                                        "> {{ legoset.statistic.today_discount }}%
                                </div>
                            </div>
                            <a href="/{{ legoset.id }}">{{ legoset.name }}</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if is_paginated %}
                <div class="pagination">
                    {% for page in page_obj.paginator.page_range %}
                        {% if page == 1 or page >= page_obj.number|add:'-3' and page <= page_obj.number|add:'3' or page == page_obj.paginator.num_pages %}
                            <a class="paginator_page_num  {% if page == page_obj.number %} active {% endif %}"
                               href="?{% paginator_url_replace request 'page' page %}">
                                {{ page }}
                            </a>
                        {% else %}
                            {% if page == page_obj.number|add:'-4' or page == page_obj.number|add:'4' %}
                                <span class="paginator_page_num">...</span>
                            {% endif %}
                        {% endif %}
                    {% endfor %}

                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

main/templates/main/series.html
{% extends 'main/main_layout.html' %}
{% load static %}

{% block title %} Все серии LEGO {% endblock %}

{% block content %}
    <div class="site_description">
        <h1>Серии LEGO:</h1>
    </div>
    <div class="index_wrapper">
        <div class="products_inner">
            {% for serie in serie_list %}
                <div class="product_wrapper div_href">
                    <div class="product_image">
                        <img src="{% static "main/images/series_logos/" %}{{ serie.id }}.png" alt="{{ serie.name }}">
                    </div>
                    <div class="product_info">
                        <div class="product_main_info">
                            <div class="serie_param">
                                <a href="/series/{{ serie.id }}">
                                    всего наборов: {{ serie.id__count }}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}